version: '3.8'

services:
  mongo:
    image: docker.io/zcube/bitnami-compat-mongodb:5.0
    container_name: fastfood-payment-mongo
    ports:
      - "27021:27017"
    networks:
      - fastfood-payment-network
    environment:
      MONGODB_USERNAME: common_user
      MONGODB_PASSWORD: password123
      MONGODB_DATABASE: fastfood
      MONGODB_ROOT_PASSWORD: rootpassword
    volumes:
      - 'mongodb_data:/fastfood'
  sqs:
    image: softwaremill/elasticmq:1.4.2
    container_name: fastfood-payment-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./sqs-compose.conf:/opt/elasticmq.conf
      - sqs_data:/data/db
    networks:
      - fastfood-payment-network

volumes:
  mongodb_data:
    driver: local
  sqs_data:
    driver: local

networks:
  fastfood-payment-network:
    driver: bridge