spring:
  application:
    name: fiap-fastfood-payment

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    mongodb:
      repositories: true
      port: ${MONGODB_PORT:27017}
      auto-index-creation: true
      uuid-representation: standard
      host: ${MONGODB_HOST:localhost}
      authentication-database: admin
      database: ${MONGODB_DATABASE:fastfood}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:rootpassword}

aws:
  sqs:
    payment:
      queue: ${SQS_QUEUE_NAME:payment_queue}
    numberOfMessages: 5
    waitTimeMessage: 10
    numberOfRetries: 10
    visibilityTimeOut: 30
    tracking:
      queue: ${TRACKING_QUEUE_NAME:tracking_queue}
    notification:
      queue: ${NOTIFICATION_QUEUE_NAME:notification_queue}
    order-cancel:
      queue: ${ORDER_CANCEL_QUEUE_NAME:order_cancellation_queue}

payment:
  webhook: ${WEBHOOK_URL:http://fastfood-payment:8080/v1/payment/receive}
  client:
    connectionTimeout: 50000
    responseTimeout: 50000
    readTimeout: 50000
    writeTimeout: 50000
    maxConnections: 5
    url: ${PAYMENT_URL:http://fastfood-payment-mock:8084}


management:
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
